//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

final generatedScreenRoutes = [
  generatedHomeScreenRoute,
  generatedWelcomeScreenRoute,
];

const SCREEN_MAKERS = [
  makerHomeScreen,
  makerWelcomeScreen,
];

Screen? findScreenFromConfiguration({
  required ModelScreenConfiguration configuration,
  required bool? isLoggedInAndVerified,
  required bool? isLoggedIn,
  required bool? isLoggedOut,
}) {
  for (final screenMaker in SCREEN_MAKERS) {
    final screen = screenMaker.call(
      configuration,
      isLoggedInAndVerified ?? false,
      isLoggedIn ?? false,
      isLoggedOut ?? true,
    );
    if (screen != null) {
      return screen;
    }
  }
  return null;
}

Screen? findScreenFromConfigurationAndAuthService({
  required ModelScreenConfiguration configuration,
  required AuthServiceInterface? authServiceBroker,
}) {
  return findScreenFromConfiguration(
    configuration: configuration,
    isLoggedInAndVerified: authServiceBroker?.loggedInAndEmailVerified ?? false,
    isLoggedIn: authServiceBroker?.loggedIn ?? false,
    isLoggedOut: authServiceBroker?.loggedOut ?? true,
  );
}
