##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: tests_app
description: Welcome to this app!
publish_to: none
version: 0.1.0+1

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  _data:
    path: ../../_data
  _service_interfaces:
    path: ../../_service_interfaces
  _services:
    path: ../../_services
  _view:
    path: ../../_view

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

## -----------------------------------------------------------------------------

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
  #   - assets/translations/
