##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: public_app
description: Welcome to Public App!
publish_to: none
version: 0.1.0+1

## -----------------------------------------------------------------------------

environment:

  sdk: '>=3.0.0 <4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter
  
  _data:
    path: ../_data
  _service_interfaces:
    path: ../_service_interfaces
  _services:
    path: ../_services
  _view:
    path: ../_view

  xyz_config: ^0.18.0
  xyz_flutter_plus: ^0.34.4
  xyz_gen_annotations: ^0.11.2
  xyz_pod: ^0.20.0
  xyz_utils: ^0.46.0

  go_router: ^13.2.0

  firebase_core: any # needed in lib/firebase_options.dart

  cupertino_icons: any
  fluentui_system_icons: any # see: https://github.com/microsoft/fluentui-system-icons/
  flutter_svg: any
  google_fonts: any
  url_launcher: any
  url_strategy: any
  visibility_detector: any
  

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: any

## -----------------------------------------------------------------------------

flutter:

  uses-material-design: true