//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'sign_up_screen.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class SignUpScreenController extends TSignUpScreenController {
  //
  //
  //

  SignUpScreenController(super.screen, super.state);

  //
  //
  //

  final pCounter = Pod<int>(-1);

  //
  //
  //

  void incrementCounter() {
    this.pCounter.update((final value) => value + 1);
  }

  //
  //
  //

  @override
  void initController() {
    this.pCounter.set(0);
    super.initController();
  }

  //
  //
  //

  @override
  void dispose() {
    // Be sure to dispose all pods here.
    this.pCounter.dispose();
    super.dispose();
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension SignUpScreenControllerExtension on SignUpScreenController {
  // Tip: You can break up your controller into multiple files using extensions.
}
