//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_bindings.g.dart';
part '_controller.dart';
part '_view.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateScreenBindings(
  defaultTitle: "Sign Up",
  isAccessibleOnlyIfLoggedOut: true,
  isRedirectable: true,
)
class SignUpScreen extends Screen {
  //
  //
  //

  const SignUpScreen({
    super.key,
    super.configuration,
    super.controllerCacheTimeout = Duration.zero,
  });

  //
  //
  //

  @override
  _View createState() => _View();

  //
  //
  //

  @override
  SignUpScreenController createController(
    Screen screen,
    ScreenView state,
  ) {
    return SignUpScreenController(screen, state);
  }
}
